---
- name: Deploy app in new namespace
  hosts: localhost # Executes ansible locally to connect with k8s
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/mauricio/Documentos/kubeconfig_myapp-eks-cluster # Address of the cluster in kubeconfig file 
    - name: Deploy nginx app
      kubernetes.core.k8s:
        src: /home/mauricio/Documentos/k8s-nginx.yaml
        state: present
        kubeconfig: /home/mauricio/Documentos/kubeconfig_myapp-eks-cluster # Location of the deployment file
        namespace: my-app # Namespace created in the task above
